Add support for TYPO3 v10.0
Nimut/TYPO3-testing-framework pull request #120
Opened 2019-09-03 15:52 UTC by bnf

2019-09-03 16:06 UTC, bnf commented
Sorry, I didn't see #118 before, therefore this patchset has some duplications – still, I think this approach is a bit cleaner:

- uses class aliases for the testbase ViewHelper
- proper site configuration handling for frontend requests
- fixes site configuration to be read from (and caches to be written to) the temporary test instance directory, instead of the original root
- Does not promise ^10.0 compatibility, just ~10.0.0

2019-09-09 17:44 UTC, bnf commented
Rebased on master to incorporate the recent removal of 7.6 support in https://github.com/Nimut/testing-framework/commit/a0737b49e32640022f8d004487df5ae0d69f4b28.

2019-10-06 17:51 UTC, simonschaufi requested changes

2019-10-06 17:51 UTC, simonschaufi commented on compat/v95/Bootstrap/Bootstrap.php
> +namespace Nimut\TestingFramework\v87\Bootstrap;
wrong namespace, or?

2019-12-03 14:14 UTC, IchHabRecht commented
Resolved with #123

2019-12-03 14:14 UTC, closed without merging